quarkus:
  hibernate-orm:
    dialect: org.hibernate.dialect.H2Dialect
    log:
      sql: 'true'
    sql-load-script: sql/import.sql
    database:
      generation: drop-and-create
  datasource:
    db-kind: h2
    jdbc:
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
